image: node:14

stages:
  - test
  - deploy
  - post

test:
  stage: test
  script:
    - npm ci
  only:
    - merge_requests
    - main

pages:
  stage: deploy
  script:
    - npm ci
    - npm run generate
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main

release:
  image: registry.gitlab.com/nosana-ci/tools/containers/semver
  stage: post
  script: release.sh
  only:
    - main